version: v2beta1
name: troubleshooting-panel-console-plugin

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: start_dev app # 5. Start dev mode "app" (see "dev" section)
  purge:
    run: stop_dev --all

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    labelSelector:
      # Use the instance selector that COO adds
      app.kubernetes.io/instance: troubleshooting-panel
    # Replace the container image with this dev-optimized image (skip image building)
    devImage: quay.io/openshift-observability-ui/troubleshooting-panel-console-plugin:devspace

    # Uncomment the following temporarily to force the cluster to pull the image.
    #
    # patches:
    #   - op: replace
    #     path: spec.containers[0].imagePullPolicy
    #     value: Always

    # Sync files between the local filesystem and the development container
    sync:
      - path: ./web/dist:/opt/app-root/web/dist
        startContainer: true
        printLogs: true
        waitInitialSync: true
    command: ["make"]
    args: ["start-devspace-backend", "FEATURES=agent-navigation"]

    ssh:
      enabled: true
