FROM registry.ci.openshift.org/ocp/builder:rhel-9-base-nodejs-openshift-5.0 AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0
COPY web/package*.json web/
COPY Makefile Makefile
RUN make install-frontend-ci

COPY web/ web/
RUN make build-frontend

FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS go-builder

WORKDIR /opt/app-root

COPY Makefile Makefile
COPY go.mod go.mod
COPY go.sum go.sum

RUN make install-backend

COPY cmd/ cmd/
COPY pkg/ pkg/

ENV GOFLAGS='-mod=mod'
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

RUN make build-backend BUILD_OPTS="-tags strictfipsruntime"

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9

RUN mkdir /licenses
COPY LICENSE /licenses/.

USER 1001

COPY --from=web-builder /opt/app-root/web/dist /opt/app-root/web/dist
COPY --from=go-builder /opt/app-root/plugin-backend /opt/app-root

ENTRYPOINT ["/opt/app-root/plugin-backend", "-static-path", "/opt/app-root/web/dist"]

ARG VERSION=v1.0.0
LABEL version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      url="https://github.com/openshift/troubleshooting-panel-console-plugin" \
      summary="OpenShift console plugin to troubleshoot by correlating observability signals" \
      io.openshift.tags="openshift,observability-ui,korrel8r,correlation" \
      io.k8s.display-name="OpenShift console troubleshooting panel plugin" \
      io.k8s.description="OpenShift console plugin to troubleshoot by correlating observability signals" \
      maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
      description="OpenShift console plugin to troubleshoot by correlating observability signals"
