// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ConsoleEventsData,
  ConsoleEventsResponse,
  ConsoleEventsResponses,
  GraphGoalsData,
  GraphGoalsErrors,
  GraphGoalsResponses,
  GraphNeighborsData,
  GraphNeighborsErrors,
  GraphNeighborsResponses,
  GraphNeighboursData,
  GraphNeighboursErrors,
  GraphNeighboursResponses,
  ListDomainClassesData,
  ListDomainClassesErrors,
  ListDomainClassesResponses,
  ListDomainsData,
  ListDomainsErrors,
  ListDomainsResponses,
  ListGoalsData,
  ListGoalsErrors,
  ListGoalsResponses,
  ObjectsData,
  ObjectsErrors,
  ObjectsResponses,
  SetConfigData,
  SetConfigResponses,
  SetConsoleData,
  SetConsoleErrors,
  SetConsoleResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Change configuration settings at runtime.
 *
 * Modify selected configuration settings (e.g. log verbosity) on a running service.
 *
 */
export const setConfig = <ThrowOnError extends boolean = false>(
  options?: Options<SetConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).put<SetConfigResponses, unknown, ThrowOnError>({
    url: '/config',
    ...options,
  });

/**
 * Get the list of correlation domains.
 *
 * Returns a list of Korrel8r domains and the stores configured for each domain.
 *
 */
export const listDomains = <ThrowOnError extends boolean = false>(
  options?: Options<ListDomainsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListDomainsResponses, ListDomainsErrors, ThrowOnError>({
    url: '/domains',
    ...options,
  });

/**
 * Get the list of classes for a domain.
 *
 * Returns a list of class names for the specified domain.
 *
 */
export const listDomainClasses = <ThrowOnError extends boolean = false>(
  options: Options<ListDomainClassesData, ThrowOnError>,
) =>
  (options.client ?? client).get<ListDomainClassesResponses, ListDomainClassesErrors, ThrowOnError>(
    { url: '/domain/{domain}/classes', ...options },
  );

/**
 * Create a correlation graph from start objects to goal queries.
 *
 * Specify a set of start objects, as queries or serialized objects, and a goal class. Returns a graph containing all paths leading from a start object to a goal object.
 *
 */
export const graphGoals = <ThrowOnError extends boolean = false>(
  options: Options<GraphGoalsData, ThrowOnError>,
) =>
  (options.client ?? client).post<GraphGoalsResponses, GraphGoalsErrors, ThrowOnError>({
    querySerializer: { parameters: { options: { object: { style: 'form' } } } },
    url: '/graphs/goals',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create a neighborhood graph around a start object to a given depth.
 *
 * Specify a set of start objects, as queries or serialized objects, and a depth for the neighborhood search. Returns a graph of all paths with depth or less edges leading from start objects.
 *
 */
export const graphNeighbors = <ThrowOnError extends boolean = false>(
  options: Options<GraphNeighborsData, ThrowOnError>,
) =>
  (options.client ?? client).post<GraphNeighborsResponses, GraphNeighborsErrors, ThrowOnError>({
    querySerializer: { parameters: { options: { object: { style: 'form' } } } },
    url: '/graphs/neighbors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create a neighborhood graph around a start object to a given depth.
 *
 * Specify a set of start objects, as queries or serialized objects, and a depth for the neighborhood search. Returns a graph of all paths with depth or less edges leading from start objects.
 *
 *
 * @deprecated
 */
export const graphNeighbours = <ThrowOnError extends boolean = false>(
  options: Options<GraphNeighboursData, ThrowOnError>,
) =>
  (options.client ?? client).post<GraphNeighboursResponses, GraphNeighboursErrors, ThrowOnError>({
    querySerializer: { parameters: { options: { object: { style: 'form' } } } },
    url: '/graphs/neighbours',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create a list of goal nodes related to a starting point.
 *
 * Specify a set of start objects, as queries or serialized objects, and a goal class. Returns a list of all objects of the goal class that can be reached from a start object.
 *
 */
export const listGoals = <ThrowOnError extends boolean = false>(
  options: Options<ListGoalsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListGoalsResponses, ListGoalsErrors, ThrowOnError>({
    url: '/lists/goals',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Execute a query, returns a list of JSON objects.
 *
 * Execute a single Korrel8r 'query' and return the list of serialized objects found. Does not perform any correlation actions.
 *
 */
export const objects = <ThrowOnError extends boolean = false>(
  options: Options<ObjectsData, ThrowOnError>,
) =>
  (options.client ?? client).get<ObjectsResponses, ObjectsErrors, ThrowOnError>({
    url: '/objects',
    ...options,
  });

/**
 * Make console state available to an agent.
 *
 * Store console state so an agent can read it via MCP tool get_console. The MCP client must have the same session (Authorization header) as the REST client.
 *
 */
export const setConsole = <ThrowOnError extends boolean = false>(
  options: Options<SetConsoleData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetConsoleResponses, SetConsoleErrors, ThrowOnError>({
    url: '/console',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * SSE event stream of console display updates from an agent.
 *
 * Updates are triggered by update requests from MCP tool show_in_console. The MCP client must have the same session (Authorization header) as the REST client.
 *
 */
export const consoleEvents = <ThrowOnError extends boolean = false>(
  options?: Options<ConsoleEventsData, ThrowOnError, ConsoleEventsResponse>,
) =>
  (options?.client ?? client).sse.get<ConsoleEventsResponses, unknown, ThrowOnError>({
    url: '/console/events',
    ...options,
  });
