// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetDomainsData,
  GetDomainsErrors,
  GetDomainsResponses,
  GetObjectsData,
  GetObjectsErrors,
  GetObjectsResponses,
  PostGraphsGoalsData,
  PostGraphsGoalsErrors,
  PostGraphsGoalsResponses,
  PostGraphsNeighboursData,
  PostGraphsNeighboursErrors,
  PostGraphsNeighboursResponses,
  PostListsGoalsData,
  PostListsGoalsErrors,
  PostListsGoalsResponses,
  PutConfigData,
  PutConfigErrors,
  PutConfigResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Change key configuration settings at runtime.
 */
export const putConfig = <ThrowOnError extends boolean = false>(
  options?: Options<PutConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).put<PutConfigResponses, PutConfigErrors, ThrowOnError>({
    url: '/config',
    ...options,
  });

/**
 * Get name, configuration and status for each domain.
 */
export const getDomains = <ThrowOnError extends boolean = false>(
  options?: Options<GetDomainsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetDomainsResponses, GetDomainsErrors, ThrowOnError>({
    url: '/domains',
    ...options,
  });

/**
 * Create a correlation graph from start objects to goal queries.
 */
export const postGraphsGoals = <ThrowOnError extends boolean = false>(
  options: Options<PostGraphsGoalsData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostGraphsGoalsResponses, PostGraphsGoalsErrors, ThrowOnError>({
    url: '/graphs/goals',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create a neighbourhood graph around a start object to a given depth.
 */
export const postGraphsNeighbours = <ThrowOnError extends boolean = false>(
  options: Options<PostGraphsNeighboursData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostGraphsNeighboursResponses,
    PostGraphsNeighboursErrors,
    ThrowOnError
  >({
    url: '/graphs/neighbours',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create a list of goal nodes related to a starting point.
 */
export const postListsGoals = <ThrowOnError extends boolean = false>(
  options: Options<PostListsGoalsData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostListsGoalsResponses, PostListsGoalsErrors, ThrowOnError>({
    url: '/lists/goals',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Execute a query, returns a list of JSON objects.
 */
export const getObjects = <ThrowOnError extends boolean = false>(
  options: Options<GetObjectsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetObjectsResponses, GetObjectsErrors, ThrowOnError>({
    url: '/objects',
    ...options,
  });
