// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | 'https://localhost:8080/api/v1alpha1'
    | 'http://localhost:8080/api/v1alpha1'
    | (string & {});
};

/**
 * Constraint constrains the objects that will be included in search results.
 */
export type Constraint = {
  /**
   * End of time interval, quoted RFC 3339 format.
   */
  end?: string | null;
  /**
   * Limit number of objects returned per query, <=0 means no limit.
   */
  limit?: number;
  /**
   * Start of time interval, quoted RFC 3339 format.
   */
  start?: string | null;
  /**
   * Timeout per request, h/m/s/ms/ns format
   */
  timeout?: string;
};

/**
 * Domain configuration information.
 */
export type Domain = {
  /**
   * Name of the domain.
   */
  name?: string;
  /**
   * Stores configured for the domain.
   */
  stores?: Array<Store>;
};

/**
 * Directed edge in the result graph, from Start to Goal classes.
 */
export type Edge = {
  /**
   * Goal is the class name of the goal node.
   */
  goal?: string;
  /**
   * Rules is the set of rules followed along this edge.
   */
  rules?: Array<Rule>;
  /**
   * Start is the class name of the start node.
   */
  start?: string;
};

/**
 * Starting point for a goals search.
 */
export type Goals = {
  /**
   * Goal classes for correlation.
   */
  goals?: Array<string>;
  start?: Start;
};

/**
 * Graph resulting from a correlation search.
 */
export type Graph = {
  edges?: Array<Edge>;
  nodes?: Array<Node>;
};

/**
 * Starting point for a neighbours search.
 */
export type Neighbours = {
  /**
   * Max depth of neighbours graph.
   */
  depth?: number;
  start?: Start;
};

/**
 * Node in the result graph, contains results for a single class.
 */
export type Node = {
  /**
   * Class is the full class name in "DOMAIN:CLASS" form.
   */
  class?: string;
  /**
   * Count of results found for this class, after de-duplication.
   */
  count?: number;
  /**
   * Queries yielding results for this class.
   */
  queries?: Array<QueryCount>;
};

/**
 * Query run during a correlation with a count of results found.
 */
export type QueryCount = {
  /**
   * Count of results or -1 if the query was not executed.
   */
  count?: number;
  /**
   * Query for correlation data.
   */
  query?: string;
};

/**
 * Rule is a correlation rule with a list of queries and results counts found during navigation.
 */
export type Rule = {
  /**
   * Name is an optional descriptive name.
   */
  name?: string;
  /**
   * Queries generated while following this rule.
   */
  queries?: Array<QueryCount>;
};

/**
 * Start identifies a set of starting objects for correlation.
 */
export type Start = {
  /**
   * Class for `objects`
   */
  class?: string;
  constraint?: Constraint;
  /**
   * Objects of `class` serialized as JSON
   */
  objects?: {
    [key: string]: unknown;
  };
  /**
   * Queries for starting objects
   */
  queries?: Array<string>;
};

/**
 * Store is a map of name:value attributes used to connect to a store.
 */
export type Store = {
  [key: string]: string;
};

export type PutConfigData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * verbose setting for logging
     */
    verbose?: number;
  };
  url: '/config';
};

export type PutConfigErrors = {
  default: unknown;
};

export type PutConfigResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetDomainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/domains';
};

export type GetDomainsErrors = {
  default: unknown;
};

export type GetDomainsResponses = {
  /**
   * OK
   */
  200: Array<Domain>;
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];

export type PostGraphsGoalsData = {
  /**
   * search from start to goal classes
   */
  body: Goals;
  path?: never;
  query?: {
    /**
     * include rules in graph edges
     */
    rules?: boolean;
  };
  url: '/graphs/goals';
};

export type PostGraphsGoalsErrors = {
  default: unknown;
};

export type PostGraphsGoalsResponses = {
  /**
   * OK
   */
  200: Graph;
  /**
   * interrupted, partial result
   */
  206: Graph;
};

export type PostGraphsGoalsResponse = PostGraphsGoalsResponses[keyof PostGraphsGoalsResponses];

export type PostGraphsNeighboursData = {
  /**
   * search from neighbours
   */
  body: Neighbours;
  path?: never;
  query?: {
    /**
     * include rules in graph edges
     */
    rules?: boolean;
  };
  url: '/graphs/neighbours';
};

export type PostGraphsNeighboursErrors = {
  default: unknown;
};

export type PostGraphsNeighboursResponses = {
  /**
   * OK
   */
  200: Graph;
  /**
   * interrupted, partial result
   */
  206: Graph;
};

export type PostGraphsNeighboursResponse =
  PostGraphsNeighboursResponses[keyof PostGraphsNeighboursResponses];

export type PostListsGoalsData = {
  /**
   * search from start to goal classes
   */
  body: Goals;
  path?: never;
  query?: never;
  url: '/lists/goals';
};

export type PostListsGoalsErrors = {
  default: unknown;
};

export type PostListsGoalsResponses = {
  /**
   * OK
   */
  200: Array<Node>;
};

export type PostListsGoalsResponse = PostListsGoalsResponses[keyof PostListsGoalsResponses];

export type GetObjectsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * query string
     */
    query: string;
  };
  url: '/objects';
};

export type GetObjectsErrors = {
  default: unknown;
};

export type GetObjectsResponses = {
  /**
   * OK
   */
  200: Array<unknown>;
};

export type GetObjectsResponse = GetObjectsResponses[keyof GetObjectsResponses];
