// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1alpha1` | (string & {});
};

/**
 * Query for data objects, format is DOMAIN:CLASS:SELECTOR. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name of a class in the domain (e.g. Pod, application, metric, alert, span, network). SELECTOR: domain-specific query string.
 *
 */
export type Query = string;

/**
 * Full name of a class of data, format is DOMAIN:CLASS. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name within the domain.
 *
 */
export type Class = string;

/**
 * Constrains the objects that will be included in search results.
 */
export type Constraint = {
  /**
   * Ignore objects with timestamps before this start time.
   */
  start?: string;
  /**
   * Ignore objects with timestamps after this end time.
   */
  end?: string;
  /**
   * Limit total number of objects per query.
   */
  limit?: number;
};

/**
 * Domain configuration information.
 */
export type Domain = {
  /**
   * Name of the domain.
   */
  name: string;
  /**
   * Brief description of the domain.
   */
  description?: string;
  /**
   * Stores configured for the domain.
   */
  stores?: Array<Store>;
};

/**
 * Directed edge in the result graph, from Start to Goal classes.
 */
export type Edge = {
  /**
   * Class name of the start node.
   */
  start: Class;
  /**
   * Class name of the goal node.
   */
  goal: Class;
  /**
   * Set of rules followed along this edge.
   */
  rules?: Array<Rule>;
};

/**
 * Error result containing an error message.
 */
export type Error = {
  /**
   * Error message.
   */
  error: string;
};

/**
 * Parameters for a goal-directed correlation search. Finds paths from start objects to goal classes.
 *
 */
export type Goals = {
  /**
   * Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert
   *
   */
  goals: Array<Class>;
  /**
   * Starting point for the search.
   */
  start: Start;
};

/**
 * Graph resulting from a correlation search.
 */
export type Graph = {
  /**
   * List of graph edges.
   */
  edges?: Array<Edge>;
  /**
   * List of graph nodes.
   */
  nodes?: Array<Node>;
};

/**
 * Parameters for a neighborhood correlation search. Finds all objects reachable from the start by following correlation rules up to the maximum depth.
 *
 */
export type Neighbors = {
  /**
   * Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only.
   *
   */
  depth: number;
  /**
   * Starting point for the search.
   */
  start: Start;
};

/**
 * Node in the result graph, contains results for a single class.
 */
export type Node = {
  /**
   * Full class name.
   */
  class: string;
  /**
   * Queries yielding results for this class.
   */
  queries?: Array<QueryCount>;
  /**
   * Number of results for this class, after de-duplication.
   */
  count?: number;
  /**
   * Serialized result contents, may be large.
   */
  result?: Array<Object>;
};

/**
 * Query with number of results.
 */
export type QueryCount = {
  /**
   * Number of results, omitted if the query was not executed.
   */
  count?: number;
  /**
   * Query for correlation data.
   */
  query: Query;
};

/**
 * Rule is a correlation rule with a list of queries and results counts found during navigation.
 */
export type Rule = {
  /**
   * Name is an optional descriptive name.
   */
  name: string;
  /**
   * Queries generated while following this rule.
   */
  queries?: Array<QueryCount>;
};

/**
 * Data object serialized as JSON.
 */
export type Object = {
  [key: string]: unknown;
};

/**
 * Starting point for a correlation search. It usually specifies queries to get the starting objects, but can include serialized objects as well as/instead of queries.
 *
 */
export type Start = {
  /**
   * Class of starting objects. Required when using 'objects' to provide serialized objects. If queries are included, they must all be of this class.
   *
   */
  class?: Class;
  /**
   * Constrains the objects that will be included in search results.
   */
  constraint?: Constraint;
  /**
   * Start objects serialized as JSON. Requires 'class' to identify the object type. Alternative to 'queries' when you already have the objects.
   *
   */
  objects?: Array<Object>;
  /**
   * Queries for starting objects in "domain:class:selector" format. This is the most common way to specify a starting point.
   *
   */
  queries?: Array<Query>;
};

/**
 * Store is a map string keys and values used to connect to a store.
 */
export type Store = {
  [key: string]: string;
};

/**
 * State of the user's graphical console display (e.g. OpenShift web console).
 *
 */
export type Console = {
  /**
   * The main console view displays the results of this query.
   */
  view?: Query;
  /**
   * The troubleshooting panel displays the results of this correlation search.
   */
  search?: Search;
};

/**
 * Correlation search parameters. Set exactly one of 'goals' (targeted search to specific classes) or 'neighbors' (open-ended exploration to a depth).
 *
 */
export type Search = {
  /**
   * Parameters for a goal-directed correlation search.
   */
  goals?: Goals;
  /**
   * Parameters for a neighborhood correlation search.
   */
  neighbors?: Neighbors;
};

/**
 * Options controlling the form of the returned graph.
 */
export type GraphOptions = {
  /**
   * If true include rule names in graph edges.
   */
  rules?: boolean;
  /**
   * If true include full JSON results with each Query.
   */
  results?: boolean;
  /**
   * If true include non-fatal error messages.
   */
  errors?: boolean;
};

export type SetConfigData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Verbose level for logging.
     */
    verbose?: number;
  };
  url: '/config';
};

export type SetConfigResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type SetConfigResponse = SetConfigResponses[keyof SetConfigResponses];

export type ListDomainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/domains';
};

export type ListDomainsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type ListDomainsError = ListDomainsErrors[keyof ListDomainsErrors];

export type ListDomainsResponses = {
  /**
   * OK
   */
  200: Array<Domain>;
};

export type ListDomainsResponse = ListDomainsResponses[keyof ListDomainsResponses];

export type ListDomainClassesData = {
  body?: never;
  path: {
    /**
     * Name of the domain to list classes for
     */
    domain: string;
  };
  query?: never;
  url: '/domain/{domain}/classes';
};

export type ListDomainClassesErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * domain not found
   */
  404: Error;
};

export type ListDomainClassesError = ListDomainClassesErrors[keyof ListDomainClassesErrors];

export type ListDomainClassesResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type ListDomainClassesResponse =
  ListDomainClassesResponses[keyof ListDomainClassesResponses];

export type GraphGoalsData = {
  /**
   * Search from start to goal classes.
   */
  body: Goals;
  path?: never;
  query?: {
    /**
     * Options controlling the form of the returned graph.
     */
    options?: {
      /**
       * If true include rule names in graph edges.
       */
      rules?: boolean;
      /**
       * If true include full JSON results with each Query.
       */
      results?: boolean;
      /**
       * If true include non-fatal error messages.
       */
      errors?: boolean;
    };
  };
  url: '/graphs/goals';
};

export type GraphGoalsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type GraphGoalsError = GraphGoalsErrors[keyof GraphGoalsErrors];

export type GraphGoalsResponses = {
  /**
   * OK
   */
  200: Graph;
};

export type GraphGoalsResponse = GraphGoalsResponses[keyof GraphGoalsResponses];

export type GraphNeighborsData = {
  /**
   * Search from start for neighbors.
   */
  body: Neighbors;
  path?: never;
  query?: {
    /**
     * Options controlling the form of the returned graph.
     */
    options?: {
      /**
       * If true include rule names in graph edges.
       */
      rules?: boolean;
      /**
       * If true include full JSON results with each Query.
       */
      results?: boolean;
      /**
       * If true include non-fatal error messages.
       */
      errors?: boolean;
    };
  };
  url: '/graphs/neighbors';
};

export type GraphNeighborsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type GraphNeighborsError = GraphNeighborsErrors[keyof GraphNeighborsErrors];

export type GraphNeighborsResponses = {
  /**
   * OK
   */
  200: Graph;
};

export type GraphNeighborsResponse = GraphNeighborsResponses[keyof GraphNeighborsResponses];

export type GraphNeighboursData = {
  /**
   * Search from start for neighbors.
   */
  body: Neighbors;
  path?: never;
  query?: {
    /**
     * Options controlling the form of the returned graph.
     */
    options?: {
      /**
       * If true include rule names in graph edges.
       */
      rules?: boolean;
      /**
       * If true include full JSON results with each Query.
       */
      results?: boolean;
      /**
       * If true include non-fatal error messages.
       */
      errors?: boolean;
    };
  };
  url: '/graphs/neighbours';
};

export type GraphNeighboursErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type GraphNeighboursError = GraphNeighboursErrors[keyof GraphNeighboursErrors];

export type GraphNeighboursResponses = {
  /**
   * OK
   */
  200: Graph;
};

export type GraphNeighboursResponse = GraphNeighboursResponses[keyof GraphNeighboursResponses];

export type ListGoalsData = {
  /**
   * Search from start to goal classes.
   */
  body: Goals;
  path?: never;
  query?: never;
  url: '/lists/goals';
};

export type ListGoalsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type ListGoalsError = ListGoalsErrors[keyof ListGoalsErrors];

export type ListGoalsResponses = {
  /**
   * OK
   */
  200: Array<Node>;
};

export type ListGoalsResponse = ListGoalsResponses[keyof ListGoalsResponses];

export type ObjectsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query string.
     */
    query: Query;
  };
  url: '/objects';
};

export type ObjectsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type ObjectsError = ObjectsErrors[keyof ObjectsErrors];

export type ObjectsResponses = {
  /**
   * OK
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ObjectsResponse = ObjectsResponses[keyof ObjectsResponses];

export type SetConsoleData = {
  /**
   * Parameters for the updated console display.
   */
  body: Console;
  path?: never;
  query?: never;
  url: '/console';
};

export type SetConsoleErrors = {
  /**
   * invalid parameters
   */
  400: Error;
};

export type SetConsoleError = SetConsoleErrors[keyof SetConsoleErrors];

export type SetConsoleResponses = {
  /**
   * Console display updated successfully
   */
  200: {
    [key: string]: unknown;
  };
};

export type SetConsoleResponse = SetConsoleResponses[keyof SetConsoleResponses];

export type ConsoleEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/console/events';
};

export type ConsoleEventsResponses = {
  /**
   * SSE stream where each event's data field contains a JSON-encoded Console object.
   *
   */
  200: Console;
};

export type ConsoleEventsResponse = ConsoleEventsResponses[keyof ConsoleEventsResponses];
