// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1alpha1` | (string & {});
};

/**
 * Represents a request to retrieve data for a particular Class. It has 3 colon-separated parts: DOMAIN:CLASS:SELECTOR. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name of a class in the domain (e.g. Pod, application, metric, alert, span, network). SELECTOR: domain-specific query string, syntax varies by domain: k8s uses JSON (e.g. {"namespace":"default","name":"my-pod"}), log uses LogQL or JSON (e.g. {"namespace":"default"}), metric uses PromQL (e.g. kube_pod_info{namespace="default"}), alert uses JSON labels (e.g. {"alertname":"KubePodCrashLooping"}), trace uses TraceQL (e.g. {resource.k8s.namespace.name="default"}), netflow uses LogQL labels (e.g. {SrcK8S_Namespace="default"}).
 *
 */
export type Query = string;

/**
 * Full name of a class of objects: DOMAIN:CLASS. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name within the domain. Examples: k8s:Pod, k8s:Deployment.apps, log:application, metric:metric, alert:alert, trace:span, netflow:network.
 *
 */
export type Class = string;

/**
 * Constrains the objects that will be included in search results.
 */
export type Constraint = {
  /**
   * Ignore objects with timestamps before this start time.
   */
  start?: string;
  /**
   * Ignore objects with timestamps after this end time.
   */
  end?: string;
  /**
   * Limit total number of objects per query.
   */
  limit?: number;
  /**
   * DEPRECATED store calls are cancelled with the request.
   */
  timeout?: Duration;
};

/**
 * The duration string is a sequence of decimal numbers, each with optional fraction and a unit suffix. Valid time units are: ns, us (or µs), ms, s, m, h.
 *
 */
export type Duration = string;

/**
 * Domain configuration information.
 */
export type Domain = {
  /**
   * Name of the domain.
   */
  name: string;
  /**
   * Brief description of the domain.
   */
  description?: string;
  /**
   * Stores configured for the domain.
   */
  stores?: Array<Store>;
};

/**
 * Directed edge in the result graph, from Start to Goal classes.
 */
export type Edge = {
  /**
   * Class name of the start node.
   */
  start: Class;
  /**
   * Class name of the goal node.
   */
  goal: Class;
  /**
   * Set of rules followed along this edge.
   */
  rules?: Array<Rule>;
};

/**
 * Error result containing an error message.
 */
export type Error = {
  /**
   * Error message.
   */
  error: string;
};

/**
 * Parameters for a goal-directed correlation search. Finds paths from start objects to the specified goal classes.
 *
 */
export type Goals = {
  /**
   * Goal classes for correlation in "domain:class" format. The search follows all paths from start to these classes. Example: ["log:application"] or ["alert:alert", "metric:metric"].
   *
   */
  goals: Array<Class>;
  /**
   * Starting point for the correlation search.
   */
  start: Start;
};

/**
 * Graph resulting from a correlation search.
 */
export type Graph = {
  /**
   * List of graph edges.
   */
  edges?: Array<Edge>;
  /**
   * List of graph nodes.
   */
  nodes?: Array<Node>;
};

/**
 * Parameters for a neighborhood correlation search. Finds all correlated objects reachable within the specified depth from start objects.
 *
 */
export type Neighbors = {
  /**
   * Maximum number of correlation steps to follow from the start. Depth 1 returns only direct correlations, depth 2 includes correlations of correlations, etc.
   *
   */
  depth: number;
  /**
   * Starting point for the correlation search.
   */
  start: Start;
};

/**
 * Node in the result graph, contains results for a single class.
 */
export type Node = {
  /**
   * Full class name
   */
  class: string;
  /**
   * Queries yielding results for this class.
   */
  queries?: Array<QueryCount>;
  /**
   * Number of results for this class, after de-duplication.
   */
  count?: number;
  /**
   * Serialized result contents, may be large.
   */
  result?: Array<Object>;
};

/**
 * Query with number of results.
 */
export type QueryCount = {
  /**
   * Number of results, omitted if the query was not executed.
   */
  count?: number;
  /**
   * Query for correlation data.
   */
  query: Query;
};

/**
 * Rule is a correlation rule with a list of queries and results counts found during navigation.
 */
export type Rule = {
  /**
   * Name is an optional descriptive name.
   */
  name: string;
  /**
   * Queries generated while following this rule.
   */
  queries?: Array<QueryCount>;
};

/**
 * Data object serialized as JSON.
 */
export type Object = {
  [key: string]: unknown;
};

/**
 * Identifies the starting point for a correlation search. Provide either 'queries' (most common) or 'class' + 'objects'.
 *
 */
export type Start = {
  /**
   * Class of starting objects. Required when using 'objects' to specify the class of the serialized objects. Optional with 'queries' since the class is embedded in each query string.
   *
   */
  class?: Class;
  /**
   * Optional time and count constraints on the objects returned by queries.
   *
   */
  constraint?: Constraint;
  /**
   * Start objects serialized as JSON. Requires 'class' to identify the object type. Alternative to 'queries' when you already have the objects.
   *
   */
  objects?: Array<Object>;
  /**
   * Queries for starting objects in "domain:class:selector" format. This is the most common way to specify a starting point. Example: ["k8s:Pod:{\"namespace\":\"default\",\"name\":\"my-pod\"}"]
   *
   */
  queries?: Array<Query>;
};

/**
 * Store is a map string keys and values used to connect to a store.
 */
export type Store = {
  [key: string]: string;
};

/**
 * State of the user's graphical console display (e.g. OpenShift web console). The query field indicates what data the console is showing. The search field optionally specifies a correlation search for the troubleshooting panel.
 *
 */
export type Console = {
  /**
   * Query the console is displaying.
   */
  query?: Query;
  /**
   * Optional correlation search for the troubleshooting panel.
   */
  search?: Search;
};

/**
 * Correlation search parameters for the console troubleshooting panel. Set exactly one of 'goals' (targeted search to specific classes) or 'neighbors' (open-ended exploration to a depth).
 *
 */
export type Search = {
  /**
   * Goal-directed search parameters (mutually exclusive with neighbors).
   */
  goals?: Goals;
  /**
   * Neighborhood search parameters (mutually exclusive with goals).
   */
  neighbors?: Neighbors;
};

/**
 * Options controlling the form of the returned graph.
 */
export type GraphOptions = {
  /**
   * If true include rule names in graph edges.
   */
  rules?: boolean;
  /**
   * If true include full JSON results with each Query.
   */
  results?: boolean;
  /**
   * if true include non-fatal error messages.
   */
  errors?: boolean;
};

export type SetConfigData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Verbose level for logging.
     */
    verbose?: number;
  };
  url: '/config';
};

export type SetConfigResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ListDomainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/domains';
};

export type ListDomainsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type ListDomainsError = ListDomainsErrors[keyof ListDomainsErrors];

export type ListDomainsResponses = {
  /**
   * OK
   */
  200: Array<Domain>;
};

export type ListDomainsResponse = ListDomainsResponses[keyof ListDomainsResponses];

export type ListDomainClassesData = {
  body?: never;
  path: {
    /**
     * Name of the domain to list classes for
     */
    domain: string;
  };
  query?: never;
  url: '/domain/{domain}/classes';
};

export type ListDomainClassesErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * domain not found
   */
  404: Error;
};

export type ListDomainClassesError = ListDomainClassesErrors[keyof ListDomainClassesErrors];

export type ListDomainClassesResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type ListDomainClassesResponse =
  ListDomainClassesResponses[keyof ListDomainClassesResponses];

export type GraphGoalsData = {
  /**
   * Search from start to goal classes.
   */
  body: Goals;
  path?: never;
  query?: {
    /**
     * Options controlling the form of the returned graph.
     */
    options?: {
      /**
       * If true include rule names in graph edges.
       */
      rules?: boolean;
      /**
       * If true include full JSON results with each Query.
       */
      results?: boolean;
      /**
       * if true include non-fatal error messages.
       */
      errors?: boolean;
    };
  };
  url: '/graphs/goals';
};

export type GraphGoalsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type GraphGoalsError = GraphGoalsErrors[keyof GraphGoalsErrors];

export type GraphGoalsResponses = {
  /**
   * OK
   */
  200: Graph;
};

export type GraphGoalsResponse = GraphGoalsResponses[keyof GraphGoalsResponses];

export type GraphNeighborsData = {
  /**
   * Search from start for neighbors.
   */
  body: Neighbors;
  path?: never;
  query?: {
    /**
     * Options controlling the form of the returned graph.
     */
    options?: {
      /**
       * If true include rule names in graph edges.
       */
      rules?: boolean;
      /**
       * If true include full JSON results with each Query.
       */
      results?: boolean;
      /**
       * if true include non-fatal error messages.
       */
      errors?: boolean;
    };
  };
  url: '/graphs/neighbors';
};

export type GraphNeighborsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type GraphNeighborsError = GraphNeighborsErrors[keyof GraphNeighborsErrors];

export type GraphNeighborsResponses = {
  /**
   * OK
   */
  200: Graph;
};

export type GraphNeighborsResponse = GraphNeighborsResponses[keyof GraphNeighborsResponses];

export type GraphNeighboursData = {
  /**
   * Search from start for neighbors.
   */
  body: Neighbors;
  path?: never;
  query?: {
    /**
     * Options controlling the form of the returned graph.
     */
    options?: {
      /**
       * If true include rule names in graph edges.
       */
      rules?: boolean;
      /**
       * If true include full JSON results with each Query.
       */
      results?: boolean;
      /**
       * if true include non-fatal error messages.
       */
      errors?: boolean;
    };
  };
  url: '/graphs/neighbours';
};

export type GraphNeighboursErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type GraphNeighboursError = GraphNeighboursErrors[keyof GraphNeighboursErrors];

export type GraphNeighboursResponses = {
  /**
   * OK
   */
  200: Graph;
};

export type GraphNeighboursResponse = GraphNeighboursResponses[keyof GraphNeighboursResponses];

export type ListGoalsData = {
  /**
   * search from start to goal classes
   */
  body: Goals;
  path?: never;
  query?: never;
  url: '/lists/goals';
};

export type ListGoalsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type ListGoalsError = ListGoalsErrors[keyof ListGoalsErrors];

export type ListGoalsResponses = {
  /**
   * OK
   */
  200: Array<Node>;
};

export type ListGoalsResponse = ListGoalsResponses[keyof ListGoalsResponses];

export type ObjectsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query string.
     */
    query: Query;
  };
  url: '/objects';
};

export type ObjectsErrors = {
  /**
   * invalid parameters
   */
  400: Error;
  /**
   * result not found
   */
  404: Error;
};

export type ObjectsError = ObjectsErrors[keyof ObjectsErrors];

export type ObjectsResponses = {
  /**
   * OK
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ObjectsResponse = ObjectsResponses[keyof ObjectsResponses];

export type SetConsoleData = {
  /**
   * Parameters for the updated console display.
   */
  body: Console;
  path?: never;
  query?: never;
  url: '/console';
};

export type SetConsoleErrors = {
  /**
   * invalid parameters
   */
  400: Error;
};

export type SetConsoleError = SetConsoleErrors[keyof SetConsoleErrors];

export type SetConsoleResponses = {
  /**
   * Console display updated successfully
   */
  200: unknown;
};

export type ConsoleEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/console/events';
};

export type ConsoleEventsResponses = {
  /**
   * Stream of console display updates.
   */
  200: unknown;
};
